In [7]:
def add(num1, num2):
    return num1 + num2

In [8]:
import module_test

In [10]:
module_test.add(10, 20)

30

In [11]:
import numpy as np

In [14]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [16]:
list1 = [1, 2, 3, 4]
arr2 = np.array(list1)
arr2

array([1, 2, 3, 4])

In [24]:
print(arr1.shape)
print(arr1.ndim)
print(arr1.size)
print(arr1.dtype)

(5,)
1
5
int32


In [27]:
arr2 = np.array([[1, 2, 3],[4, 5, 6]])
arr2.ndim

2

In [28]:
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
arr3.shape

(2, 2, 2)

In [36]:
arr3.ndim

3

In [37]:
arr3.size

8

In [38]:
arr_zeros = np.zeros((3, 4))
print(arr_zeros)
print(arr_zeros.ndim)
arr_ones = np.ones((3, 4))
print(arr_ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [39]:
arr_full = np.full((5, 5), 7)
arr_full

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [40]:
list = []
for i in range(1, 51):
    list.append(i)
print(list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [41]:
arr4 = np.arange(1, 51)
arr4

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [42]:
arr4 = np.arange(1, 51, 10)
arr4

array([ 1, 11, 21, 31, 41])

In [43]:
arr_type = np.array([1.2, 2.3, 3.4], dtype = np.int64)
arr_type

array([1, 2, 3], dtype=int64)

In [45]:
arr_type = arr_type.astype("float64")
arr_type.dtype

dtype('float64')

In [49]:
arr = np.random.rand(2, 3)
arr

array([[0.49737282, 0.77939615, 0.77715447],
       [0.02542898, 0.18015281, 0.00213133]])

In [53]:
arr = np.random.randint(2, 10)
arr

6

In [54]:
arr = np.random.randint(2, 10, size = (2, 3))
arr

array([[8, 8, 7],
       [6, 4, 2]])

In [55]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [59]:
print(arr + arr)
print(arr * arr)

[2 4 6]
[1 4 9]


In [60]:
data = np.loadtxt("height_weight.txt", delimiter = ",", encoding = "euc_kr")
data

array([[175.2, 180.3, 175. , 169.2, 185.2, 188. , 177.6, 178.2, 177. ,
        179. ],
       [ 65.6,  88. ,  79.2,  69.3,  55. ,  71.2,  73. ,  68.9,  74. ,
         82. ]])